ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Copy configuration and alerting rules
COPY prom.yml /etc/prometheus/prom.yml
COPY rules /etc/prometheus/rules

# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus", "--storage.tsdb.no-lockfile"]
